class VolunteerOpportunity {
  final String id;
  final String title;
  final String description;
  final String organizationName;
  final String category;
  final String imageUrl;
  final String logoUrl;
  final DateTime date;
  final String startTime;
  final String endTime;
  final String location;
  final int requiredVolunteers;
  final int currentVolunteers;
  final double rating;
  final int voteCount;
  final double distance;
  bool isFavorite;
  final bool isDestaque;

  VolunteerOpportunity({
    required this.id,
    required this.title,
    required this.description,
    required this.organizationName,
    required this.category,
    required this.imageUrl,
    required this.date,
    required this.startTime,
    required this.endTime,
    required this.location,
    required this.requiredVolunteers,
    required this.currentVolunteers,
    this.rating = 0.0,
    this.voteCount = 0,
    this.distance = 0.0,
    this.isFavorite = false,
    this.isDestaque = false,
    required this.logoUrl,
  });
}

final List<VolunteerOpportunity> mockOpportunities = [
  VolunteerOpportunity(
    id: '1',
    title: 'Banho em Cães de Abrigo',
    description:
        'Precisamos de voluntários para ajudar na higiene dos cães resgatados.',
    organizationName: 'Amigo Bicho',
    category: 'Animais',
    imageUrl:
        'https://images.unsplash.com/photo-1548191265-cc70d3d45ba1?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/124598?v=3',
    date: DateTime.now().add(const Duration(days: 3)),
    startTime: '09:00',
    endTime: '12:00',
    location: 'Abrigo Municipal de Animais',
    requiredVolunteers: 5,
    currentVolunteers: 2,
    rating: 4.7,
    voteCount: 85,
    distance: 3.5,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '2',
    title: 'Distribuição de Alimentos',
    description:
        'Ajude na organização e entrega de marmitas para moradores de rua.',
    organizationName: 'Ação Solidária',
    category: 'Alimentação',
    imageUrl:
        'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/124597?v=3',
    date: DateTime.now().add(const Duration(days: 2)),
    startTime: '14:00',
    endTime: '16:00',
    location: 'Praça da Matriz',
    requiredVolunteers: 10,
    currentVolunteers: 4,
    rating: 4.9,
    voteCount: 128,
    distance: 1.2,
    isFavorite: true,
  ),
  VolunteerOpportunity(
    id: '3',
    title: 'Oficina de Leitura Infantil',
    description:
        'Contação de histórias e atividades lúdicas para crianças de 4 a 10 anos.',
    organizationName: 'Futuro Brilhante',
    category: 'Crianças e Jovens',
    imageUrl:
        'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/124599?v=3',
    date: DateTime.now().add(const Duration(days: 4)),
    startTime: '10:00',
    endTime: '12:00',
    location: 'Biblioteca Comunitária',
    requiredVolunteers: 6,
    currentVolunteers: 2,
    rating: 4.8,
    voteCount: 72,
    distance: 2.3,
    isFavorite: true,
  ),
  VolunteerOpportunity(
    id: '4',
    title: 'Visita Recreativa a Idosos',
    description:
        'Tarde de música, jogos e conversas com idosos no lar da terceira idade.',
    organizationName: 'Viver Bem',
    category: 'Idosos',
    imageUrl:
        'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/101010?v=3',
    date: DateTime.now().add(const Duration(days: 5)),
    startTime: '15:00',
    endTime: '17:00',
    location: 'Lar da Terceira Idade',
    requiredVolunteers: 8,
    currentVolunteers: 3,
    rating: 4.6,
    voteCount: 53,
    distance: 4.3,
    isFavorite: true,
  ),
  VolunteerOpportunity(
    id: '5',
    title: 'Limpeza de Rio Local',
    description: 'Mutirão para retirada de lixo das margens do rio da cidade.',
    organizationName: 'EcoVida',
    category: 'Meio Ambiente',
    imageUrl:
        'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/202020?v=3',
    date: DateTime.now().add(const Duration(days: 6)),
    startTime: '07:30',
    endTime: '11:00',
    location: 'Marginal Oeste',
    requiredVolunteers: 30,
    currentVolunteers: 12,
    rating: 4.3,
    voteCount: 97,
    distance: 8.1,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '6',
    title: 'Aula de Reforço Escolar',
    description:
        'Ensino de matemática e português para jovens em situação de vulnerabilidade.',
    organizationName: 'Educa Mais',
    category: 'Educação',
    imageUrl:
        'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/303030?v=3',
    date: DateTime.now().add(const Duration(days: 7)),
    startTime: '18:00',
    endTime: '19:30',
    location: 'Centro Comunitário',
    requiredVolunteers: 4,
    currentVolunteers: 1,
    rating: 4.8,
    voteCount: 64,
    distance: 2.0,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '7',
    title: 'Campanha de Doação de Sangue',
    description:
        'Apoie na organização e acolhimento de doadores no hemocentro municipal.',
    organizationName: 'Saúde para Todos',
    category: 'Saúde',
    imageUrl:
        'https://images.unsplash.com/photo-1615461066841-6116e61058f4?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/404040?v=3',
    date: DateTime.now().add(const Duration(days: 8)),
    startTime: '08:00',
    endTime: '13:00',
    location: 'Hemocentro Municipal',
    requiredVolunteers: 12,
    currentVolunteers: 5,
    rating: 4.9,
    voteCount: 140,
    distance: 3.0,
    isFavorite: true,
  ),
  VolunteerOpportunity(
    id: '8',
    title: 'Oficina de Grafite Comunitário',
    description:
        'Pintura de mural coletivo para revitalizar espaços públicos do bairro.',
    organizationName: 'Arte na Rua',
    category: 'Cultura e Arte',
    imageUrl:
        'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/505050?v=3',
    date: DateTime.now().add(const Duration(days: 9)),
    startTime: '09:00',
    endTime: '16:00',
    location: 'Largo da Cultura',
    requiredVolunteers: 10,
    currentVolunteers: 4,
    rating: 4.5,
    voteCount: 38,
    distance: 1.8,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '9',
    title: 'Aula de Informática para Idosos',
    description:
        'Ensine o básico de celular e computador para quem nunca teve acesso.',
    organizationName: 'Conecta Brasil',
    category: 'Tecnologia',
    imageUrl:
        'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/606060?v=3',
    date: DateTime.now().add(const Duration(days: 10)),
    startTime: '14:00',
    endTime: '16:00',
    location: 'Telecentro Municipal',
    requiredVolunteers: 5,
    currentVolunteers: 1,
    rating: 4.7,
    voteCount: 46,
    distance: 5.5,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '10',
    title: 'Escolinha de Futebol Social',
    description:
        'Treine e motive crianças carentes através do esporte em campo comunitário.',
    organizationName: 'Gol Solidário',
    category: 'Esportes',
    imageUrl:
        'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/707070?v=3',
    date: DateTime.now().add(const Duration(days: 11)),
    startTime: '16:00',
    endTime: '18:00',
    location: 'Campo do Bairro Novo',
    requiredVolunteers: 8,
    currentVolunteers: 3,
    rating: 4.6,
    voteCount: 59,
    distance: 6.2,
    isFavorite: true,
  ),
  VolunteerOpportunity(
    id: '11',
    title: 'Mutirão de Reforma Comunitária',
    description:
        'Pintura e pequenos reparos na sede da associação de moradores.',
    organizationName: 'Bairro Vivo',
    category: 'Geral / Outros',
    imageUrl:
        'https://images.unsplash.com/photo-1596464716127-f2a82984de30?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/808080?v=3',
    date: DateTime.now().add(const Duration(days: 12)),
    startTime: '08:00',
    endTime: '12:00',
    location: 'Associação de Moradores',
    requiredVolunteers: 20,
    currentVolunteers: 7,
    rating: 4.4,
    voteCount: 42,
    distance: 4.0,
    isFavorite: false,
  ),
  VolunteerOpportunity(
    id: '12',
    title: 'Castração Solidária de Gatos',
    description:
        'Ajude a organizar o mutirão de castração gratuita para gatos de rua.',
    organizationName: 'Patinhas Felizes',
    category: 'Animais',
    imageUrl:
        'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/909090?v=3',
    date: DateTime.now().add(const Duration(days: 13)),
    startTime: '08:00',
    endTime: '14:00',
    location: 'Clínica Veterinária Popular',
    requiredVolunteers: 10,
    currentVolunteers: 4,
    rating: 4.8,
    voteCount: 91,
    distance: 2.7,
    isFavorite: false,
    isDestaque: true,
  ),
  VolunteerOpportunity(
    id: '13',
    title: 'Feira de Saúde Comunitária',
    description:
        'Aferição de pressão, orientação nutricional e triagem básica para a comunidade.',
    organizationName: 'Saúde na Praça',
    category: 'Saúde',
    imageUrl:
        'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/101112?v=3',
    date: DateTime.now().add(const Duration(days: 14)),
    startTime: '09:00',
    endTime: '15:00',
    location: 'Praça Central',
    requiredVolunteers: 15,
    currentVolunteers: 6,
    rating: 4.9,
    voteCount: 112,
    distance: 1.5,
    isFavorite: true,
    isDestaque: true,
  ),
  VolunteerOpportunity(
    id: '14',
    title: 'Plantio de Árvores Nativas',
    description:
        'Reflorestamento de área degradada com espécies nativas da Mata Atlântica.',
    organizationName: 'Raízes Verdes',
    category: 'Meio Ambiente',
    imageUrl:
        'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/131415?v=3',
    date: DateTime.now().add(const Duration(days: 15)),
    startTime: '07:00',
    endTime: '11:30',
    location: 'Reserva Ambiental Norte',
    requiredVolunteers: 25,
    currentVolunteers: 10,
    rating: 4.7,
    voteCount: 78,
    distance: 9.3,
    isFavorite: false,
    isDestaque: false,
  ),
  VolunteerOpportunity(
    id: '15',
    title: 'Mentoria de Redação para o ENEM',
    description:
        'Auxilie jovens de escolas públicas na preparação de redações para o ENEM.',
    organizationName: 'Aprovação Já',
    category: 'Educação',
    imageUrl:
        'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/161718?v=3',
    date: DateTime.now().add(const Duration(days: 16)),
    startTime: '19:00',
    endTime: '21:00',
    location: 'Escola Estadual São José',
    requiredVolunteers: 6,
    currentVolunteers: 2,
    rating: 4.6,
    voteCount: 55,
    distance: 3.8,
    isFavorite: false,
    isDestaque: false,
  ),
  VolunteerOpportunity(
    id: '16',
    title: 'Corrida Beneficente 5km',
    description:
        'Ajude na organização da corrida solidária com renda revertida para o hospital infantil.',
    organizationName: 'Corra pelo Bem',
    category: 'Esportes',
    imageUrl:
        'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?q=80&w=400',
    logoUrl: 'https://app.requestly.io/delay/2000/avatars.githubusercontent.com/u/192021?v=3',
    date: DateTime.now().add(const Duration(days: 17)),
    startTime: '06:30',
    endTime: '10:00',
    location: 'Parque da Cidade',
    requiredVolunteers: 20,
    currentVolunteers: 8,
    rating: 4.5,
    voteCount: 67,
    distance: 4.5,
    isFavorite: true,
    isDestaque: false,
  ),
];
